spring:
  application:
    name: pages-management-service
s3:
  part:
    size: 5242880
  configuration:
    accessKey: minio
    secretKey: minio123
    location: http://s3:9000
server:
  port: 8080
